import { notFound } from "next/navigation";
import { requireAdmin } from "@/server/auth/guard";
import { getCampaign } from "@/server/campaigns/service";
import { getSettings } from "@/server/settings/settings";
import {
  getCampaignMetrics, getCampaignTimeSeries, getCampaignResults,
} from "@/server/analytics/service";
import { RatesBarChart, TimeSeriesChart } from "@/components/charts";

export const dynamic = "force-dynamic";

/**
 * Print-friendly campaign report. Reused by the PDF export (Playwright renders
 * this route to PDF) so the figures match the on-screen dashboard styling. Guarded
 * by requireAdmin — the PDF route forwards the admin's session cookie.
 */
export default async function CampaignPrintReport({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  await requireAdmin();
  const { id } = await params;
  const [campaign, settings] = await Promise.all([getCampaign(id), getSettings()]);
  if (!campaign) notFound();
  const [metrics, series, results] = await Promise.all([
    getCampaignMetrics(id), getCampaignTimeSeries(id), getCampaignResults(id),
  ]);

  const rateData = [
    { name: "Open", value: metrics.openRate },
    { name: "Click", value: metrics.clickRate },
    { name: "Submit", value: metrics.submissionRate },
    { name: "Report", value: metrics.reportRate },
    { name: "Phish-prone", value: metrics.phishProne },
  ];

  return (
    <main className="mx-auto max-w-3xl bg-white px-8 py-10 text-ink-900">
      <header className="mb-6 border-b border-ink-300 pb-4">
        <p className="text-xs uppercase tracking-wide text-ink-500">{settings.orgName} · Phishing simulation report</p>
        <h1 className="mt-1 text-2xl font-bold">{campaign.name}</h1>
        <p className="mt-1 text-sm text-ink-500">
          Template: {campaign.emailTemplate.name} · Status: {campaign.status}
          {campaign.launchedAt ? ` · Launched ${campaign.launchedAt.toLocaleString()}` : ""}
        </p>
      </header>

      <section className="mb-6 grid grid-cols-3 gap-3">
        {[
          { label: "Delivered", value: metrics.delivered },
          { label: "Open rate", value: `${metrics.openRate}%` },
          { label: "Click rate", value: `${metrics.clickRate}%` },
          { label: "Submit rate", value: `${metrics.submissionRate}%` },
          { label: "Report rate", value: `${metrics.reportRate}%` },
          { label: "Phish-prone", value: `${metrics.phishProne}%` },
        ].map((m) => (
          <div key={m.label} className="rounded border border-ink-200 p-3 text-center">
            <p className="text-xl font-bold">{m.value}</p>
            <p className="text-xs text-ink-500">{m.label}</p>
          </div>
        ))}
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-sm font-semibold text-ink-600">Engagement rates</h2>
        <RatesBarChart data={rateData} />
      </section>

      {series.length > 0 && (
        <section className="mb-6">
          <h2 className="mb-2 text-sm font-semibold text-ink-600">Events over time (minutes since launch)</h2>
          <TimeSeriesChart data={series} />
        </section>
      )}

      <section>
        <h2 className="mb-2 text-sm font-semibold text-ink-600">Per-recipient results ({results.length})</h2>
        <table className="w-full border-collapse text-xs">
          <thead>
            <tr className="border-b border-ink-300 text-left text-ink-500">
              <th className="py-1.5">Recipient</th><th>Department</th><th>Opened</th><th>Clicked</th><th>Submitted</th><th>Reported</th><th>Quiz</th>
            </tr>
          </thead>
          <tbody>
            {results.map((r, i) => (
              <tr key={i} className="border-b border-ink-100">
                <td className="py-1">{r.firstName} {r.lastName}</td>
                <td>{r.department ?? "—"}</td>
                <td>{r.opened ? "✓" : ""}</td>
                <td>{r.clicked ? "✓" : ""}</td>
                <td>{r.submitted ? "✓" : ""}</td>
                <td>{r.reported ? "✓" : ""}</td>
                <td>{r.quizScore}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <footer className="mt-8 border-t border-ink-300 pt-3 text-xs text-ink-500">
        Generated by Phlare · authorised internal security-awareness training · synthetic/authorised data only.
      </footer>
    </main>
  );
}
